### ISSUE TITLE
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.2.0/plugins/inspect/groups_inspector.rb:40:in `block in parse_groups': undefined method `split' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by DanielZuck** [SUSE/machinery#596] opened 2015-02-16 14:23 UTC
# machinery inspect localhost
Inspecting localhost for changed-managed-files, config-files, groups, os, packages, patterns, repositories, services, unmanaged-files, users...
Inspecting changed-managed-files...
 -> Found 21 changed files.
Inspecting config-files...
 -> Found 40 changed configuration files.
Inspecting groups...
Machinery experienced an unexpected error. Please file a bug report at https://github.com/SUSE/machinery/issues/new.
/usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.2.0/plugins/inspect/groups_inspector.rb:40:in `block in parse_groups': undefined method `split' for nil:NilClass (NoMethodError)
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.2.0/plugins/inspect/groups_inspector.rb:31:in `map'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.2.0/plugins/inspect/groups_inspector.rb:31:in `parse_groups'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.2.0/plugins/inspect/groups_inspector.rb:22:in `inspect'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.2.0/lib/inspect_task.rb:78:in `block in build_description'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.2.0/lib/inspect_task.rb:75:in `each'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.2.0/lib/inspect_task.rb:75:in `build_description'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.2.0/lib/inspect_task.rb:23:in `inspect_system'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.2.0/lib/cli.rb:459:in `block (2 levels) in <class:Cli>'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.2.0/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `call'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.2.0/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.2.0/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.2.0/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.2.0/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.2.0/bundle/ruby/2.1.0/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
	from /usr/lib64/ruby/gems/2.1.0/gems/machinery-tool-1.2.0/bin/machinery:26:in `<top (required)>'
	from /usr/bin/machinery:26:in `load'
	from /usr/bin/machinery:26:in `<main>'
root@host:~# rpm -qi machinery
Name        : machinery
Version     : 1.2.0
Release     : 12.2
Architecture: x86_64
Install Date: Mon 16 Feb 2015 03:18:48 PM CET
Group       : Development/Languages/Ruby
Size        : 22801226
License     : GPL-3.0
Signature   : RSA/SHA256, Mon 12 Jan 2015 01:23:12 PM CET, Key ID 70af9e8139db7c82
Source RPM  : machinery-1.2.0-12.2.src.rpm
Build Date  : Wed 07 Jan 2015 02:27:33 PM CET
Build Host  : sheep23
Relocations : (not relocatable)
Packager    : https://www.suse.com/
Vendor      : SUSE LLC <https://www.suse.com/>
URL         : http://suse.com
Summary     : Systems management toolkit
Description :
Machinery is a systems management toolkit for Linux. It supports configuration
discovery, system validation, and service migration. It's based on the idea of a
universal system description.
Distribution: SUSE Linux Enterprise 12
root@host:~# uname -a
Linux host 3.12.32-33-default #1 SMP Fri Dec 19 20:03:01 UTC 2014 (a2814e9) x86_64 x86_64 x86_64 GNU/Linux

**Comment by thardeck** [comment] 2015-02-20 16:26
Hi, thx for your report. I think I was able to reproduce the issue.

I have already created a pull request to fix it. To be sure that I reproduced your issue can you try something on the system which you inspected?

Can you check if there is a nis placeholder `+:::` at the end of the file `/etc/group` on the system you inspected? If there is not then please attach the file (Make sure that there is no private data in it before).

If there is a nis placeholder than the reason for the issue is most likely the missing newline at the end of the file. You could add one until the new machinery version is released but make sure to create a backup of the file before.

If you want to inspect your system without the groups scope just run: `machinery inspect --exclude-scope=groups <hostname>`

**Comment by thardeck** [comment] 2015-02-23 12:58
This should be fixed by #623 but it needs confirmation since we didn't have the original file which caused the error.

**Comment by DanielZuck** [comment] 2015-03-16 10:18
The issue was raised doing a generic call to machinery on a freshly installed system.

The intention behind was not to sort out something very specific, but a very generic sneak into the tool to get to know to it. Saying that, the error was sort of disappointing...

**Closed** 2015-04-02 15:35 UTC
Labels: Bug, P2, to be validated
