### ISSUE TITLE
'machinery config perform-support-check=false' does still show the support check message once

### ISSUE THREAD

**Issue by greygoo** [SUSE/machinery#1249] opened 2015-08-25 08:39 UTC
When running machinery on a non supported platform you get this message:

------------------snip--------------------
s390vsw144:~ # machinery list
You are running Machinery on a platform we do not explicitly support and test.
It still could work very well. If you run into issues or would like to provide us feedback, you are welcome to file an issue at https://github.com/SUSE/machinery/issues/new or write an email to machinery@lists.suse.com.
Oficially supported operating systems are: 'SUSE Linux Enterprise Server 12, openSUSE 13.1 (Bottle), openSUSE 13.2 (Harlequin), openSUSE Tumbleweed'

To disable this message in the machinery configuration use 'machinery config perform-support-check=false'
------------------snip--------------------

However, when running the suggested command - the same message still gets displayed, my expectation would be that this command does not show any such output - especially output telling the user to run the command he just executed to get rid of the message:

------------------snip--------------------
s390vsw144:~ # machinery config perform-support-check=false
You are running Machinery on a platform we do not explicitly support and test.
It still could work very well. If you run into issues or would like to provide us feedback, you are welcome to file an issue at https://github.com/SUSE/machinery/issues/new or write an email to machinery@lists.suse.com.
Oficially supported operating systems are: 'SUSE Linux Enterprise Server 12, openSUSE 13.1 (Bottle), openSUSE 13.2 (Harlequin), openSUSE Tumbleweed'

To disable this message in the machinery configuration use 'machinery config perform-support-check=false'
perform-support-check=false
------------------snip--------------------

After this last message - machinery is silent though, so it is only about the output for the config command.

**Comment by promulo** [comment] 2016-03-18 10:41
Hi @greygoo is this still valid? I could not reproduce (Fedora here).

**Comment by mauromorales** [comment] 2016-03-22 09:17
Closing since we don't have this concept of "supported systems" since 1.16.3

Thanks for looking into this @promulo :)

**Closed by mauromorales** 2016-03-22 09:17 UTC
Labels: Bug
