### ISSUE TITLE
--skip-files=/ leads to invalid system description

### ISSUE THREAD

**Issue by tgoettlicher** [SUSE/machinery#693] opened 2015-03-12 10:00 UTC
--skip-files=/ leads to invalid system description
```
# machinery inspect myhost -x  --scope unmanaged-files --skip-files=/ 
# machinery validate myhost
Validation failed.
In scope unmanaged_files: The property (files) of type Array matched more than one of the required schemas.
```

**Comment by cornelius** [comment] 2015-03-12 10:47
Could this be a duplicate of #680 ?

**Comment by aduffeck** [comment] 2015-03-12 14:21
I think it is.

**Closed by aduffeck** 2015-03-12 14:21 UTC
