### ISSUE TITLE
Config files table is not aligned properly in HTML view

### ISSUE THREAD

**Issue by cornelius** [SUSE/machinery#1900] opened 2016-01-25 11:44 UTC
The config files table is not aligned as the other scopes are. See screenshot.
![machinery-html-view](https://cloud.githubusercontent.com/assets/23799/12550014/4d2841b0-c361-11e5-8aeb-0e621dee0c6e.png)

**Comment by thardeck** [comment] 2016-01-25 13:38
Duplicate of #1814

**Closed by thardeck** 2016-01-25 13:38 UTC
