### ISSUE TITLE
When already a firefox instance is running,"machinery show localhost --html" fails

### ISSUE THREAD

**Issue by coderabhishek** [SUSE/machinery#1951] opened 2016-02-04 16:46 UTC
machinery show localhost --html 
Above command shows correct result if no Firefox instance is currently running but if one is already open it doesn't opens a new window or a new tab instead following error is shown:

Firefox is already running, but is not responding. To open a new window, you must first close the existing Firefox process, or restart your system.

Though running instance of Firefox is responding fine.
I have not checked this for any other browser.

**Comment by mauromorales** [comment] 2016-02-08 16:18
Thanks for reporting the issue @coderabhishek, will try to reproduce and get back to you

**Comment by mauromorales** [comment] 2016-03-04 08:33
@coderabhishek couldn't reproduce ... even if I have an instance of FF running machinery get's started correctly.

Closing for now but if you have any additional information on how to reproduce please let me know.

Cheers!

**Closed by mauromorales** 2016-03-04 08:33 UTC
Labels: Bug, P2
