### ISSUE TITLE
Remove default `Link is invalid` page of Sinatra

### ISSUE THREAD

**Issue by mschnitzer** [SUSE/machinery#1636] opened 2015-11-11 08:11 UTC
I tried to access my description via IP address but the link was not valid and the default error 404 page of Sinatra was shown We should replace this page with a self created error 404 page.

![sinatra](https://cloud.githubusercontent.com/assets/8287131/11086709/26cef6dc-8854-11e5-8ecd-b7375eb0db6d.png)

**Comment by tgoettlicher** [comment] 2015-11-13 13:34
This is a duplicate of https://github.com/SUSE/machinery/issues/1198

**Closed by tgoettlicher** 2015-11-13 13:34 UTC
Labels: Enhancement
