### ISSUE TITLE
Running Machinery with non-root user

### ISSUE THREAD

**Issue by gsanso** [SUSE/machinery#610] opened 2015-02-18 10:36 UTC
Currently one of the main requisites for running machinery is ssh root access enabled on the inspected host.

For sysadmins It's common practice to disable root user ssh login for security reasons.

It could be a nice feature to be able to run Machinery with non privileged user.

**Comment by ajaeger** [comment] 2015-02-19 14:12
Duplicate of https://github.com/SUSE/machinery/issues/586

**Closed by ajaeger** 2015-02-19 14:12 UTC
